### ISSUE TITLE
Feature request: Move information

### ISSUE THREAD

**Issue by snorrewb** [Sidaroth/PokedexService#1]
I propose a function that pulls info for a move including:
- Type
- Power
- Accuracy
- Description
- Base PP
- TM/HM number

**Comment by snorrewb** [comment]
Could also list what types have immunity/weakness/resistance!

**Comment by Sidaroth** [comment]
http://pokeapi.co/api/v2/ability/20

or
http://pokeapi.co/api/v2/ability/stall

certainly gives information about abilities, so this should be possible.

**Comment by Sidaroth** [comment]
Added in 757e62ed2853ac1143366d51025f35d0215335b9, in addition to abilities. Closing.
