### ISSUE TITLE
Extended information: Regular dex lookup

### ISSUE THREAD

**Issue by snorrewb** [Sidaroth/PokedexService#2]
I request adding extended commands to /dex, showing us variant information in addition to or instead of regular info. For example `/dex -breed 123` and possibly a shorthand `/dex -b 123`.
### Breeding info.
- Egg group (steps to hatch).
- Egg moves, TM moves, leveling moves.
### Evolution info.
- To/from.
- Method of each listed evolution.

**Comment by snorrewb** [comment]
### Abilities.

Should describe all abilities and denote which one is Hidden.

**Comment by Sidaroth** [comment]
Information about abilities have been added, as evolution chains and breeds are now seperate issues (#29 and #19) I will close this issue.
